#!/bin/sh

# Find which is your current branch
if currentBranch=$(git symbolic-ref --short -q HEAD)
protectedBranch=master
then
    echo On branch "$currentBranch"
    git push -u origin $currentBranch
else
    echo ERROR: Cannot find the current branch!
fi
